version: "3"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - ${APP_PORT}:3000
    environment:
      - GF_SERVER_ROOT_URL=https://${APP_URL}/
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_SECURITY_DISABLE_GRAVATAR=${DISABLE_GRAVATAR}
      - GF_ANALYTICS_REPORTING_ENABLED=${REPORTING_ENABLED}
      - GF_ANALYTICS_CHECK_FOR_UPDATES=${CHECK_FOR_UPDATES}
      - GF_SMTP_ENABLED=${SMTP_ENABLED}
      - GF_SMTP_HOST=${SMTP_HOST}
      - GF_SMTP_USER=${SMTP_USER}
      - GF_SMTP_PASSWORD=${SMTP_PASSWORD}
      - GF_SMTP_FROM_ADDRESS=${SMTP_USER}
    volumes:
      - grafana:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.grafana.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
    networks:
      - traefik_default
      - default
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=${DB_NAME}
      - INFLUXDB_ADMIN_USER=${DB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${DB_ADMIN_PASSWORD}
      - INFLUXDB_USER=${DB_NAME}
      - INFLUXDB_USER_PASSWORD=${DB_USER_PASSWORD}
    volumes:
      - influxdb:/var/lib/influxdb
    networks:
      - default
volumes:
  grafana:
  influxdb:
networks:
  traefik_default:
    external: true
  default:
