version: "3"
services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_NAME}
    networks:
      - default
  redis:
    image: redis
    restart: always
    networks:
      - default
  app:
    build: ./build/app
    restart: always
    volumes:
      - data:/var/www/html
    environment:
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_PASSWORD=${DB_PASSWORD}  
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_NAME}
    depends_on:
      - db
      - redis
    networks:
      - default
  web:
    build: ./build/web
    restart: always
    ports:
      - ${APP_PORT}:80
    volumes:
      - data:/var/www/html
    depends_on:
      - app
    networks:
      - default
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.nextcloud.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls=true"
  cron:
    build: ./build/app
    restart: always
    volumes:
      - data:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    networks:
      - default
volumes:
  data:
  db:
networks:
  default:
  traefik_default:
    external: true
