version: '3'
services:
  grocy:
    image: linuxserver/grocy
    container_name: grocy
    environment:
      - TZ=${APP_TIMEZONE}
    volumes:
      - data:/config
    ports:
      - ${APP_PORT}:80
    restart: always
    networks:
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.grocy.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.grocy.entrypoints=websecure"
      - "traefik.http.routers.grocy.tls=true"
volumes:
  data:
networks:
  traefik_default:
    external:
      name: traefik_default
